# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run NPM scripts

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  turbo:
    name: Install and test repository
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Cache Trubo
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo

      - name: Yarn install
        run: yarn --frozen-lockfile

      - name: Yarn test
        # FIXME test for lint:strict when go to production
        run: yarn test --cache-dir=.turbo
