# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run NPM scripts

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  yarn:
    name: Install dependencies
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Yarn install
        run: yarn --frozen-lockfile

  test:
    name: Test repository
    runs-on: ubuntu-latest
    environment: production
    needs: yarn

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Yarn install
        run: yarn --frozen-lockfile

      - name: Cache Trubo
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-test

      - name: Yarn test
        run: yarn test --cache-dir=.turbo

  lint:
    name: Lint repository
    runs-on: ubuntu-latest
    environment: production
    needs: yarn
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Yarn install
        run: yarn --frozen-lockfile

      - name: Cache Trubo
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-lint

      - name: Yarn lint:strict
        run: yarn lint:strict --cache-dir=.turbo
